-- SmartStudent sample data
-- Generated: students, subjects, student_marks
-- roll_no format: YY + 3-letter dept code + 7 digits (12 chars total, VARCHAR)

-- ============ students ============
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26MCA0533224', 'APP131244', 'Aarav Mukherjee', 'Male', 'SC', 'Buddhist', 'Ishaan Mukherjee', 'Anika Mukherjee', '6338908386', '7794026542', '221, Hostel Block C, Near West Delhi Road, West Delhi', '105, Gandhi Nagar 12, West Delhi, Delhi', 'West Delhi', 'Delhi', '542417', 'BCA', 'Computer Applications', '2nd', 44);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26COM3226067', 'APP838797', 'Deepika Verma', 'Female', 'EWS', 'Muslim', 'Harsh Verma', 'Kritika Verma', '6034131647', '8255341928', '747, Hostel Block B, Near Durgapur Road, Durgapur', '168, Civil Lines 30, Durgapur, West Bengal', 'Durgapur', 'West Bengal', '705397', 'B.Com', 'Commerce', '7th', 6);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26MCA9515702', 'APP852787', 'Gitanjali Das', 'Female', 'ST', 'Buddhist', 'Yash Das', 'Diya Das', '8376724238', '8969653287', '94, Hostel Block A, Near Ahmedabad Road, Ahmedabad', '882, Gandhi Nagar 6, Ahmedabad, Gujarat', 'Ahmedabad', 'Gujarat', '321231', 'BCA', 'Computer Applications', '6th', 26);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26ACF4476583', 'APP905934', 'Rahul Patel', 'Male', 'General', 'Christian', 'Suresh Patel', 'Kritika Patel', '8146270482', '6489325288', '941, Hostel Block A, Near Bikaner Road, Bikaner', '614, Model Town , Bikaner, Rajasthan', 'Bikaner', 'Rajasthan', '887352', 'B.Com', 'Accounting and Finance', '1st', 44);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26COM8937326', 'APP903035', 'Anika Verma', 'Female', 'EWS', 'Muslim', 'Krishna Verma', 'Jyoti Verma', '7278248963', '7465787133', '66, Hostel Block C, Near Bhubaneswar Road, Bhubaneswar', '22, Ashok Vihar , Bhubaneswar, Odisha', 'Bhubaneswar', 'Odisha', '897549', 'B.Com', 'Commerce', '2nd', 47);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26MCA3993055', 'APP392004', 'Aditya Banerjee', 'Male', 'General', 'Muslim', 'Anil Banerjee', 'Diya Banerjee', '9382997376', '7116566701', '63, Hostel Block D, Near Bengaluru Road, Bengaluru', '746, Model Town , Bengaluru, Karnataka', 'Bengaluru', 'Karnataka', '639131', 'BCA', 'Computer Applications', '1st', 56);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26CHM9232926', 'APP202664', 'Reyansh Rao', 'Male', 'EWS', 'Jain', 'Sandeep Rao', 'Aadhya Rao', '6801326773', '9026064746', '714, Hostel Block D, Near Gurgaon Road, Gurgaon', '159, Shastri Nagar 2, Gurgaon, Haryana', 'Gurgaon', 'Haryana', '564656', 'B.Sc', 'Chemistry', '5th', 30);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26ACF9983032', 'APP171262', 'Harsh Rathore', 'Male', 'General', 'Hindu', 'Vivaan Rathore', 'Diya Rathore', '7619399091', '9998543534', '406, Hostel Block B, Near North Delhi Road, North Delhi', '688, Sector 11, North Delhi, Delhi', 'North Delhi', 'Delhi', '171849', 'B.Com', 'Accounting and Finance', '3rd', 4);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26COM6199635', 'APP398830', 'Meera Naidu', 'Female', 'SC', 'Buddhist', 'Vihaan Naidu', 'Ira Naidu', '7784980841', '7411824493', '735, Hostel Block C, Near Chennai Road, Chennai', '209, Sector , Chennai, Tamil Nadu', 'Chennai', 'Tamil Nadu', '356150', 'B.Com', 'Commerce', '5th', 9);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26CSE5596150', 'APP908577', 'Ishita Malhotra', 'Female', 'OBC', 'Jain', 'Naveen Malhotra', 'Isha Malhotra', '7427868011', '7805982620', '316, Hostel Block C, Near Ahmedabad Road, Ahmedabad', '921, Gandhi Nagar , Ahmedabad, Gujarat', 'Ahmedabad', 'Gujarat', '103717', 'B.Tech', 'Computer Science Engineering', '7th', 54);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26ACF2970445', 'APP532322', 'Vikram Singh', 'Male', 'SC', 'Christian', 'Aman Singh', 'Charu Singh', '6256342160', '9337543303', '409, Hostel Block C, Near Faridabad Road, Faridabad', '286, Gandhi Nagar , Faridabad, Haryana', 'Faridabad', 'Haryana', '938742', 'B.Com', 'Accounting and Finance', '3rd', 60);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26CSE7290770', 'APP462479', 'Rani Agarwal', 'Female', 'ST', 'Christian', 'Amit Agarwal', 'Neha Agarwal', '8698169340', '9088356159', '322, Hostel Block A, Near Ahmedabad Road, Ahmedabad', '738, Model Town , Ahmedabad, Gujarat', 'Ahmedabad', 'Gujarat', '213668', 'B.Tech', 'Computer Science Engineering', '5th', 12);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26MCA9192860', 'APP974224', 'Anjali Chauhan', 'Female', 'OBC', 'Hindu', 'Amit Chauhan', 'Aadhya Chauhan', '6443699577', '9387214895', '96, Hostel Block B, Near Gwalior Road, Gwalior', '689, Model Town 7, Gwalior, Madhya Pradesh', 'Gwalior', 'Madhya Pradesh', '525800', 'BCA', 'Computer Applications', '7th', 44);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26ENG6705062', 'APP355836', 'Krishna Menon', 'Male', 'OBC', 'Jain', 'Suresh Menon', 'Isha Menon', '7016328708', '7172788957', '628, Hostel Block D, Near Patiala Road, Patiala', '851, Ashok Vihar , Patiala, Punjab', 'Patiala', 'Punjab', '618392', 'BA', 'English', '8th', 27);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26POL1299954', 'APP848206', 'Kritika Tiwari', 'Female', 'EWS', 'Jain', 'Yash Tiwari', 'Anika Tiwari', '8345581223', '9231665876', '64, Hostel Block B, Near Panipat Road, Panipat', '853, Civil Lines 25, Panipat, Haryana', 'Panipat', 'Haryana', '561239', 'BA', 'Political Science', '8th', 41);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26ZOO7030010', 'APP664365', 'Siddharth Malhotra', 'Male', 'ST', 'Christian', 'Yash Malhotra', 'Swati Malhotra', '7734670656', '7729806990', '86, Hostel Block D, Near Siliguri Road, Siliguri', '139, Civil Lines 9, Siliguri, West Bengal', 'Siliguri', 'West Bengal', '994905', 'B.Sc', 'Zoology', '1st', 23);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26MAT9049949', 'APP154615', 'Sandeep Rathore', 'Male', 'General', 'Buddhist', 'Karan Rathore', 'Charu Rathore', '8310033092', '7271937452', '621, Hostel Block A, Near East Delhi Road, East Delhi', '797, Shastri Nagar , East Delhi, Delhi', 'East Delhi', 'Delhi', '120324', 'B.Sc', 'Mathematics', '7th', 17);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26ZOO5059717', 'APP991597', 'Naveen Chauhan', 'Male', 'ST', 'Sikh', 'Manish Chauhan', 'Rani Chauhan', '6905865185', '6671657262', '752, Hostel Block C, Near Gurgaon Road, Gurgaon', '631, Ashok Vihar , Gurgaon, Haryana', 'Gurgaon', 'Haryana', '831059', 'B.Sc', 'Zoology', '4th', 5);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26ECE6358385', 'APP452737', 'Neha Bansal', 'Female', 'ST', 'Sikh', 'Krishna Bansal', 'Gitanjali Bansal', '6752735454', '8808313678', '777, Hostel Block B, Near Kozhikode Road, Kozhikode', '708, Civil Lines , Kozhikode, Kerala', 'Kozhikode', 'Kerala', '739979', 'B.Tech', 'Electronics and Communication Engineering', '8th', 16);
INSERT INTO students (roll_no, application_number, name, gender, category, religion, father_name, mother_name, student_phone, parent_phone, temporary_address, permanent_address, district, state, pincode, course, department, current_semester, division) VALUES ('26BBA8907391', 'APP460455', 'Aditya Chauhan', 'Male', 'OBC', 'Christian', 'Krishna Chauhan', 'Sneha Chauhan', '9855744431', '7518233749', '779, Hostel Block C, Near Tiruchirappalli Road, Tiruchirappalli', '103, Shastri Nagar 12, Tiruchirappalli, Tamil Nadu', 'Tiruchirappalli', 'Tamil Nadu', '680358', 'BBA', 'Business Administration', '5th', 43);

-- ============ subjects ============
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CSE100', 'Data Structures', 'B.Tech', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CSE101', 'Database Management Systems', 'B.Tech', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CSE102', 'Operating Systems', 'B.Tech', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CSE103', 'Computer Networks', 'B.Tech', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CSE104', 'Object Oriented Programming', 'B.Tech', '5th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CSE105', 'Web Technologies', 'B.Tech', '6th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CSE106', 'Software Engineering', 'B.Tech', '7th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CSE107', 'Theory of Computation', 'B.Tech', '8th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CSE108', 'Compiler Design', 'B.Tech', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CSE109', 'Artificial Intelligence', 'B.Tech', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ITE100', 'Data Structures', 'B.Tech', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ITE101', 'Database Management Systems', 'B.Tech', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ITE102', 'Computer Networks', 'B.Tech', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ITE103', 'Web Technologies', 'B.Tech', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ITE104', 'Cloud Computing', 'B.Tech', '5th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ITE105', 'Information Security', 'B.Tech', '6th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ITE106', 'Mobile App Development', 'B.Tech', '7th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ECE100', 'Digital Electronics', 'B.Tech', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ECE101', 'Signals and Systems', 'B.Tech', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ECE102', 'Analog Electronics', 'B.Tech', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ECE103', 'Microprocessors', 'B.Tech', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ECE104', 'Communication Systems', 'B.Tech', '5th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ECE105', 'VLSI Design', 'B.Tech', '6th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('EEE100', 'Circuit Theory', 'B.Tech', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('EEE101', 'Electrical Machines', 'B.Tech', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('EEE102', 'Power Systems', 'B.Tech', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('EEE103', 'Control Systems', 'B.Tech', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('EEE104', 'Electrical Measurements', 'B.Tech', '5th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MEC100', 'Thermodynamics', 'B.Tech', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MEC101', 'Fluid Mechanics', 'B.Tech', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MEC102', 'Machine Design', 'B.Tech', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MEC103', 'Manufacturing Processes', 'B.Tech', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MEC104', 'Strength of Materials', 'B.Tech', '5th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CIV100', 'Structural Analysis', 'B.Tech', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CIV101', 'Surveying', 'B.Tech', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CIV102', 'Geotechnical Engineering', 'B.Tech', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CIV103', 'Building Materials', 'B.Tech', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CIV104', 'Fluid Mechanics', 'B.Tech', '5th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MCA100', 'Programming in C', 'BCA', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MCA101', 'Data Structures', 'BCA', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MCA102', 'Database Management Systems', 'BCA', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MCA103', 'Java Programming', 'BCA', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MCA104', 'Web Development', 'BCA', '5th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MCA105', 'Computer Networks', 'BCA', '6th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('PHY100', 'Mechanics', 'B.Sc', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('PHY101', 'Electromagnetism', 'B.Sc', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('PHY102', 'Thermodynamics', 'B.Sc', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('PHY103', 'Optics', 'B.Sc', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('PHY104', 'Quantum Mechanics', 'B.Sc', '5th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CHM100', 'Organic Chemistry', 'B.Sc', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CHM101', 'Inorganic Chemistry', 'B.Sc', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CHM102', 'Physical Chemistry', 'B.Sc', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('CHM103', 'Analytical Chemistry', 'B.Sc', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MAT100', 'Calculus', 'B.Sc', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MAT101', 'Linear Algebra', 'B.Sc', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MAT102', 'Differential Equations', 'B.Sc', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('MAT103', 'Probability and Statistics', 'B.Sc', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ZOO100', 'Animal Physiology', 'B.Sc', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ZOO101', 'Genetics', 'B.Sc', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ZOO102', 'Ecology', 'B.Sc', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ZOO103', 'Cell Biology', 'B.Sc', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('BOT100', 'Plant Physiology', 'B.Sc', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('BOT101', 'Plant Taxonomy', 'B.Sc', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('BOT102', 'Ecology', 'B.Sc', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('BOT103', 'Cell Biology', 'B.Sc', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('COM100', 'Financial Accounting', 'B.Com', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('COM101', 'Business Studies', 'B.Com', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('COM102', 'Economics', 'B.Com', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('COM103', 'Business Law', 'B.Com', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ACF100', 'Financial Accounting', 'B.Com', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ACF101', 'Cost Accounting', 'B.Com', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ACF102', 'Taxation', 'B.Com', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ACF103', 'Auditing', 'B.Com', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('BBA100', 'Principles of Management', 'BBA', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('BBA101', 'Marketing Management', 'BBA', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('BBA102', 'Human Resource Management', 'BBA', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('BBA103', 'Business Communication', 'BBA', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ENG100', 'British Literature', 'BA', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ENG101', 'American Literature', 'BA', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ENG102', 'Linguistics', 'BA', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ENG103', 'Literary Criticism', 'BA', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('HIS100', 'Ancient Indian History', 'BA', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('HIS101', 'Medieval Indian History', 'BA', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('HIS102', 'Modern Indian History', 'BA', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('HIS103', 'World History', 'BA', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('POL100', 'Political Theory', 'BA', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('POL101', 'Indian Government and Politics', 'BA', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('POL102', 'International Relations', 'BA', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('POL103', 'Public Administration', 'BA', '4th');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ECO100', 'Microeconomics', 'BA', '1st');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ECO101', 'Macroeconomics', 'BA', '2nd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ECO102', 'Indian Economy', 'BA', '3rd');
INSERT INTO subjects (subject_id, subject_name, course, semester) VALUES ('ECO103', 'Statistics for Economics', 'BA', '4th');

-- ============ student_marks ============
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA0533224', 'MCA105', '6th', 41, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA0533224', 'MCA104', '5th', 51, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA0533224', 'MCA101', '2nd', 97, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA0533224', 'MCA103', '4th', 36, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26COM3226067', 'COM102', '3rd', 41, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26COM3226067', 'COM101', '2nd', 96, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26COM3226067', 'COM103', '4th', 43, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26COM3226067', 'COM100', '1st', 44, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA9515702', 'MCA105', '6th', 0, 100, 'Absent');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA9515702', 'MCA100', '1st', 88, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA9515702', 'MCA101', '2nd', 63, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA9515702', 'MCA104', '5th', 83, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA9515702', 'MCA103', '4th', 91, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA9515702', 'MCA102', '3rd', 89, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ACF4476583', 'ACF100', '1st', 68, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ACF4476583', 'ACF102', '3rd', 55, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ACF4476583', 'ACF103', '4th', 44, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ACF4476583', 'ACF101', '2nd', 87, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26COM8937326', 'COM103', '4th', 71, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26COM8937326', 'COM101', '2nd', 93, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26COM8937326', 'COM100', '1st', 64, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26COM8937326', 'COM102', '3rd', 0, 100, 'Absent');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA3993055', 'MCA104', '5th', 0, 100, 'Absent');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA3993055', 'MCA101', '2nd', 44, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA3993055', 'MCA103', '4th', 74, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA3993055', 'MCA100', '1st', 71, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA3993055', 'MCA102', '3rd', 94, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA3993055', 'MCA105', '6th', 86, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CHM9232926', 'CHM103', '4th', 76, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CHM9232926', 'CHM101', '2nd', 38, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CHM9232926', 'CHM100', '1st', 37, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CHM9232926', 'CHM102', '3rd', 0, 100, 'Absent');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ACF9983032', 'ACF102', '3rd', 91, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ACF9983032', 'ACF103', '4th', 0, 100, 'Absent');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ACF9983032', 'ACF100', '1st', 90, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ACF9983032', 'ACF101', '2nd', 97, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26COM6199635', 'COM103', '4th', 48, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26COM6199635', 'COM101', '2nd', 77, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26COM6199635', 'COM102', '3rd', 98, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26COM6199635', 'COM100', '1st', 86, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CSE5596150', 'CSE100', '1st', 86, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CSE5596150', 'CSE107', '8th', 35, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CSE5596150', 'CSE101', '2nd', 94, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CSE5596150', 'CSE102', '3rd', 59, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CSE5596150', 'CSE106', '7th', 98, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CSE5596150', 'CSE105', '6th', 41, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ACF2970445', 'ACF102', '3rd', 97, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ACF2970445', 'ACF103', '4th', 65, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ACF2970445', 'ACF100', '1st', 74, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ACF2970445', 'ACF101', '2nd', 87, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CSE7290770', 'CSE103', '4th', 54, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CSE7290770', 'CSE101', '2nd', 72, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CSE7290770', 'CSE107', '8th', 69, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26CSE7290770', 'CSE100', '1st', 96, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA9192860', 'MCA101', '2nd', 0, 100, 'Absent');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA9192860', 'MCA103', '4th', 52, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA9192860', 'MCA105', '6th', 70, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA9192860', 'MCA104', '5th', 88, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MCA9192860', 'MCA100', '1st', 99, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ENG6705062', 'ENG100', '1st', 92, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ENG6705062', 'ENG101', '2nd', 79, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ENG6705062', 'ENG102', '3rd', 83, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ENG6705062', 'ENG103', '4th', 76, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26POL1299954', 'POL101', '2nd', 87, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26POL1299954', 'POL102', '3rd', 95, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26POL1299954', 'POL103', '4th', 83, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26POL1299954', 'POL100', '1st', 54, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ZOO7030010', 'ZOO100', '1st', 91, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ZOO7030010', 'ZOO103', '4th', 93, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ZOO7030010', 'ZOO101', '2nd', 53, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ZOO7030010', 'ZOO102', '3rd', 54, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MAT9049949', 'MAT103', '4th', 77, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MAT9049949', 'MAT101', '2nd', 83, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MAT9049949', 'MAT102', '3rd', 0, 100, 'Absent');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26MAT9049949', 'MAT100', '1st', 97, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ZOO5059717', 'ZOO100', '1st', 71, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ZOO5059717', 'ZOO102', '3rd', 0, 100, 'Absent');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ZOO5059717', 'ZOO103', '4th', 90, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ZOO5059717', 'ZOO101', '2nd', 0, 100, 'Absent');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ECE6358385', 'ECE105', '6th', 42, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ECE6358385', 'ECE100', '1st', 82, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ECE6358385', 'ECE103', '4th', 66, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ECE6358385', 'ECE104', '5th', 58, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ECE6358385', 'ECE101', '2nd', 45, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26ECE6358385', 'ECE102', '3rd', 83, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26BBA8907391', 'BBA101', '2nd', 67, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26BBA8907391', 'BBA103', '4th', 36, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26BBA8907391', 'BBA100', '1st', 94, 100, 'Present');
INSERT INTO student_marks (roll_no, subject_id, semester_recorded, marks_obtained, total_marks, attendance_status) VALUES ('26BBA8907391', 'BBA102', '3rd', 0, 100, 'Absent');